backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "lifestyle"
    label: "Lifestyle articles"
    folder: "src/pages/lifestyle"
    create: true
    slug: "{{fields.titleEN}}"
    fields:       
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lifestyle-post"}
      - {label: "Titel ENGLISH", name: "titleEN", widget: "string"}
      - {label: "Titel DEUTSCH", name: "titleDE", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Beschreibung ENGLISH", name: "descriptionEN", widget: "text"}
      - {label: "Beschreibung DEUTSCH", name: "descriptionDE", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Artikelbild", name: "featuredimage", widget: image}
      - {label: "Artikel ENGLISH", name: "bodyEN", widget: "markdown"}
      - {label: "Artikel DEUTSCH", name: "bodyDE", widget: "markdown"}
      - {label: "Schlagwörter in Englisch", name: "tags", widget: "list", required: false}
  
  - name: "recipe"
    label: "Recipes"
    folder: "src/pages/recipe"
    create: true
    slug: "{{fields.titleEN}}"
    fields:       
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recipe-post"}
      - {label: "Titel ENGLISH", name: "titleEN", widget: "string"}
      - {label: "Titel DEUTSCH", name: "titleDE", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Beschreibung ENGLISH", name: "descriptionEN", widget: "text"}
      - {label: "Beschreibung DEUTSCH", name: "descriptionDE", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Artikelbild", name: "featuredimage", widget: image}
      - {label: "Einleitung ENGLISH", name: "introEN", widget: "markdown", required: false}
      - {label: "Zutatenliste ENGLISH", name: "ingredientlistEN", widget: "list", fields: [{label: Amount, name: amount, widget: string}, {label: Ingredient, name: ingredient, widget: string}]}
      - {label: "Arbeitsschritte ENGLISH", name: "instructionsEN", widget: "markdown"}
      - {label: "Einleitung DEUTSCH", name: "introDE", widget: "markdown", required: false}
      - {label: "Zutatenliste DEUTSCH", name: "ingredientlistDE", widget: "list", fields: [{label: Menge, name: amount, widget: string}, {label: Zutat, name: ingredient, widget: string}]}
      - {label: "Arbeitsschritte DEUTSCH", name: "instructionsDE", widget: "markdown"}
      - {label: "Schlagwörter in Englisch", name: "tags", widget: "list", required: false}

  - name: "fitness"
    label: "Fitness articles"
    folder: "src/pages/fitness"
    create: true
    slug: "{{fields.titleEN}}"
    fields:       
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fitness-post"}
      - {label: "Titel ENGLISH", name: "titleEN", widget: "string"}
      - {label: "Titel DEUTSCH", name: "titleDE", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Beschreibung ENGLISH", name: "descriptionEN", widget: "text"}
      - {label: "Beschreibung DEUTSCH", name: "descriptionDE", widget: "text"}
      - {label: "Post auf Startseite", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Artikelbild", name: "featuredimage", widget: image}
      - {label: "Artikel ENGLISH", name: "bodyEN", widget: "markdown"}
      - {label: "Artikel DEUTSCH", name: "bodyDE", widget: "markdown"}
      - {label: "Schlagwörter in Englisch", name: "tags", widget: "list", required: false}

  - name: "brands"
    label: "Markenlogos"
    folder: "src/pages/brands"
    create: true
    slug: "{{fields.templateKey}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "brands"}
      - {label: "Logo Marke 1", name: "logo1", widget: image, required: false}
      - {label: "Beschreibung Marke 1 DE", name: "brand1de", widget: string, required: false}
      - {label: "Beschreibung Marke 1 EN", name: "brand1en", widget: string, required: false}
      - {label: "Beschreibung Marke 1 Link", name: "brand1link", widget: string, required: false}
      - {label: "Logo Marke 2", name: "logo2", widget: image, required: false}
      - {label: "Beschreibung Marke 2 DE", name: "brand2de", widget: string, required: false}
      - {label: "Beschreibung Marke 2 EN", name: "brand2en", widget: string, required: false}
      - {label: "Beschreibung Marke 2 Link", name: "brand2link", widget: string, required: false}
      - {label: "Logo Marke 3", name: "logo3", widget: image, required: false}
      - {label: "Beschreibung Marke 3 DE", name: "brand3de", widget: string, required: false}
      - {label: "Beschreibung Marke 3 EN", name: "brand3en", widget: string, required: false}
      - {label: "Beschreibung Marke 3 Link", name: "brand3link", widget: string, required: false}